// Auto-generated by svelte-realtime — do not edit
// Provides client-side types for $live/ imports

declare module '$live/boards/activity' {
  import type { Readable } from 'svelte/store';
  import type { RpcError } from 'svelte-realtime/client';

  export const activity: (...args: any[]) => Readable<any>;
}

declare module '$live/boards/cursors' {
  export const joinBoard: (...args: any[]) => Promise<any>;
  export const leaveBoard: (...args: any[]) => Promise<any>;
  export const moveCursor: (...args: any[]) => Promise<any>;
}

declare module '$live/boards/notes' {
  import type { Readable } from 'svelte/store';
  import type { RpcError } from 'svelte-realtime/client';

  export const createNote: (...args: any[]) => Promise<any>;
  export const moveNote: (...args: any[]) => Promise<any>;
  export const editNote: (...args: any[]) => Promise<any>;
  export const focusNote: (...args: any[]) => Promise<any>;
  export const deleteNote: (...args: any[]) => Promise<any>;
  export const tidyNotes: (...args: any[]) => Promise<any>;
  export const rearrangeNotes: (...args: any[]) => Promise<any>;
  export const shuffleNotes: (...args: any[]) => Promise<any>;
  export const groupByAuthor: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORBIDDEN' | 'NOT_FOUND' | 'VALIDATION';
  export const notes: (...args: any[]) => Readable<any>;
}

declare module '$live/boards/settings' {
  import type { Readable } from 'svelte/store';
  import type { RpcError } from 'svelte-realtime/client';

  export const updateSettings: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'NOT_FOUND' | 'VALIDATION';
  export const settings: (...args: any[]) => Readable<any>;
}

declare module '$live/boards' {
  import type { Readable } from 'svelte/store';
  import type { RpcError } from 'svelte-realtime/client';

  export const createBoard: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'SERVER_ERROR';
  export const boards: Readable<any>;
}
