// Auto-generated by svelte-realtime -- do not edit
// Provides client-side types for $live/ imports

declare module '$live/boards/activity' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const activity: ((...args: any[]) => StreamStore<any>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/boards/cursors' {
  import type { RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const joinBoard: (...args: any[]) => Promise<any>;
  export const leaveBoard: (...args: any[]) => Promise<any>;
  export const moveCursor: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'OVERLOADED';
  export const empty: Readable<undefined>;
}

declare module '$live/boards/notes' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const moveNote: (...args: any[]) => Promise<any>;
  export const focusNote: (...args: any[]) => Promise<any>;
  export const deleteNote: (...args: any[]) => Promise<any>;
  export const tidyNotes: (...args: any[]) => Promise<any>;
  export const rearrangeNotes: (...args: any[]) => Promise<any>;
  export const shuffleNotes: (...args: any[]) => Promise<any>;
  export const groupByAuthor: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORBIDDEN' | 'NOT_FOUND' | 'VALIDATION';
  export const notes: ((...args: any[]) => StreamStore<any>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const editNote: (...args: any[]) => Promise<any>;
  export const createNote: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/boards/settings' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const updateSettings: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'NOT_FOUND' | 'VALIDATION';
  export const settings: ((...args: any[]) => StreamStore<any>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/boards' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export type ErrorCode = 'SERVER_ERROR';
  export const boards: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const createBoard: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/demos/auctions' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myAuctionsState: (...args: any[]) => Promise<any>;
  export const createAuction: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'VALIDATION';
  export const activeAuctions: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const recentResults: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/chaos' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const startChaos: (...args: any[]) => Promise<any>;
  export const stopChaos: (...args: any[]) => Promise<any>;
  export const myChaosState: (...args: any[]) => Promise<any>;
  export const chaosTicks: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/chat' {
  import type { StreamStore } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const sendMessage: (...args: any[]) => Promise<any>;
  export const chat: { data: (...args: any[]) => StreamStore<any>, presence?: (...args: any[]) => StreamStore<any>, cursors?: (...args: any[]) => StreamStore<any>, [action: string]: (...args: any[]) => Promise<any> | ((...args: any[]) => StreamStore<any>) };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/checkout' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const reset: (...args: any[]) => Promise<any>;
  export const count: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const placeOrder: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/demos/cluster-cron' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myClusterCronState: (...args: any[]) => Promise<any>;
  export const clusterTicks: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/counter-resume' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const reset: (...args: any[]) => Promise<any>;
  export const count: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/denials' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myOrg: (...args: any[]) => Promise<any>;
  export const appendEntry: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORBIDDEN' | 'UNAUTHENTICATED' | 'VALIDATION';
  export const auditLog: ((...args: any[]) => StreamStore<any>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/effect' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myEffectState: (...args: any[]) => Promise<any>;
  export const placeOrder: (...args: any[]) => Promise<any>;
  export const clearFeeds: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'VALIDATION';
  export const ordersStream: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const auditStream: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const notificationsStream: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/flash-sales' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myFlashState: (...args: any[]) => Promise<any>;
  export const resetSale: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'SOLD_OUT' | 'VALIDATION';
  export const productList: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const recentSales: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const buyProduct: (...args: any[]) => Promise<any>;
  export const claimCoupon: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/demos/from-seq' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myFromSeqState: (...args: any[]) => Promise<any>;
  export const eventStream: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/jobs' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myJobsState: (...args: any[]) => Promise<any>;
  export const enqueueJob: (...args: any[]) => Promise<any>;
  export const forceTakeover: (...args: any[]) => Promise<any>;
  export const clearJobs: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'UNAVAILABLE' | 'VALIDATION';
  export const jobsList: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const jobsStats: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/news' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myNewsState: (...args: any[]) => Promise<any>;
  export const setSpeed: (...args: any[]) => Promise<any>;
  export const signPublish: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'VALIDATION';
  export const newsStories: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const newsStats: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const trending: {
    "last30s": StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
    "thisMinute": StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
    "lifetime": StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/notifications' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const sendNotification: (...args: any[]) => Promise<any>;
  export const cancelScheduled: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'NOT_FOUND' | 'VALIDATION';
  export const scheduledNotifications: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const recentActivity: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/pagination' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myPaginationState: (...args: any[]) => Promise<any>;
  export const appendLogEntry: (...args: any[]) => Promise<any>;
  export const logFeed: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/pressure' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const generateLoad: (...args: any[]) => Promise<any>;
  export const simulateShed: (...args: any[]) => Promise<any>;
  export const clearShedLog: (...args: any[]) => Promise<any>;
  export const pressureSnapshot: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const shedEvents: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/schema-evolution' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myCounterState: (...args: any[]) => Promise<any>;
  export const incrementCounter: (...args: any[]) => Promise<any>;
  export const resetCounters: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'VALIDATION';
  export const counter: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/todos-rollback' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const addTodo: (...args: any[]) => Promise<any>;
  export const toggleTodo: (...args: any[]) => Promise<any>;
  export const removeTodo: (...args: any[]) => Promise<any>;
  export const clearAll: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORCED' | 'FULL' | 'NOT_FOUND' | 'VALIDATION';
  export const todosStream: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/topk' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const setSpeed: (...args: any[]) => Promise<any>;
  export const setBias: (...args: any[]) => Promise<any>;
  export const myTopkState: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'VALIDATION';
  export const trending: {
    "last10s": StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
    "last1min": StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
    "thisMinute": StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
    "lifetime": StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  };
  export const empty: Readable<undefined>;
}

declare module '$live/demos/upload' {
  import type { StreamStore, RpcError, UploadHandle } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const myUploadState: (...args: any[]) => Promise<any>;
  export const clearFiles: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'CANCELLED' | 'VALIDATION';
  export const uploadedFiles: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const uploadStats: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const uploadFile: (source: Blob | ArrayBuffer | ArrayBufferView | ReadableStream<Uint8Array>, ...args: any[]) => UploadHandle<any>;
  export const empty: Readable<undefined>;
}
